<a href="https://colab.research.google.com/github/ValReies/analisis-datos-i/blob/main/Portafolio_Alexa_Valentina_Sanchez_Reyes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://shop.cocoatechnologies.mx/public/portals/686156949/siteResources/9464000011257386" width="180"
align="rigth">

###

# **Universidad Anáhuac Oaxaca**

# **Materia:** Análisis de Datos 1

# **Portafolio de evidencias**

#

**Nombre del alumno:**
Alexa Valentina Sanchez Reyes

**ID:**
00607953

**Nombre del docente:**
Conrado Javier Jimenez Mendez

**Escuela de Negocios**

**Carrera:**
Negocios Internacionales

**Parcial:** 01

**Lugar y fecha:**
Blvd. Guadalupe Hinojosa de Murat No. 1100. San Raymundo Jalpan, Oaxaca C.P. 71280

11 de septiembre de 2026.

###**UNIDAD 1**
##1 · La pregunta y los datos

##**Ficha de la fuente**

**Nombre de la fuente:** Banco Mundial - Indicadores de Desarrollo Mundial (World Bank Open Data API).

**Descripción:** Base de datos global que recopila indicadores macroeconómicos y sociales normalizados para todos los países miembros.

**Acceso:** API REST pública. Descarga verificada, sin token, devuelve JSON limpio.
**Cita:** Banco Mundial. (2026). World Development Indicators. Recuperado de la API oficial.

**Actualización:** Datos actualizados al 13 de julio de 2026.

**1. Quién levanta el dato y con qué propósito:**
El indicador es publicado por el Banco Mundial, pero recopilado a partir de fuentes oficiales nacionales (en el caso de México, datos del INEGI y Banco de México). El propósito del Banco Mundial al unificar estos datos es monitorear el desarrollo económico global, ayudar en el diseño de políticas públicas y evaluar las economías a nivel internacional de forma estandarizada.

**2. Cobertura:**
Periodo: Series de tiempo anuales (la API extrae los últimos años disponibles, generalmente desde 1960 a la actualidad).
Geografía y universo: Nivel país (México). Contempla la producción total formal de bienes y servicios dentro de las fronteras.
Qué queda fuera: La economía informal y el trabajo no remunerado (tareas domésticas, cuidado), ya que el PIB no captura estas transacciones.

**3. Unidad de observación:**
Cada renglón de nuestra tabla representa el reporte de un país en un año específico (Ej. México en el año 2023).

**4. Cómo se llega al dato publicado:**
Es una estimación agregada. Se calcula mediante el Sistema de Cuentas Nacionales del país. El Banco Mundial toma esa suma en moneda local y la convierte a dólares estadounidenses (USD corrientes) usando el tipo de cambio oficial de mercado, permitiendo comparar a México con el resto del mundo.

**5. Licencia y cita:**
Licencia: Creative Commons Atribución 4.0 Internacional (CC BY 4.0).
Cita: Banco Mundial. (2026). World Development Indicators: PIB (US$ a precios actuales). Indicador NY.GDP.MKTP.CD. Recuperado a través de la API pública.

**6. Qué pregunta NO puedes responder con esta fuente (aunque parezca que sí):**
No se puede responder "¿Han mejorado los mexicanos su calidad de vida y poder adquisitivo?". El PIB total nos dice el tamaño de la economía, pero no nos dice cómo se distribuye esa riqueza (desigualdad) ni contempla el costo de las cosas dentro del país (inflación local).

In [42]:
library(jsonlite)
library(tidyverse)

In [43]:
url <- "https://api.worldbank.org/v2/country/MEX/indicator/NY.GDP.MKTP.CD?format=json&per_page=100"

In [55]:
datos_crudos <- read_csv(url)

New names:
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...8`
• `country:{id:MX` -> `country:{id:MX...9`
• `value:Mexico}` -> `value:Mexico}...10`
• `countryiso3code:MEX` -> `countryiso3code:MEX...11`
• `unit:"` -> `unit:"...14`
• `obs_status:"` -> `obs_status:"...15`
• `decimal:0}` -> `decimal:0}...16`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...17`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...18`
• `country:{id:MX` -> `country:{id:MX...19`
• `value:Mexico}` -> `value:Mexico}...20`
• `countryiso3code:MEX` -> `countryiso3code:MEX...21`
• `unit:"` -> `unit:"...24`
• `obs_status:"` -> `obs_status:"...25`
• `decimal:0}` -> `decimal:0}...26`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...27`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...28`
• `country:{id:MX` -> `country:{id:MX...29`
• `value:Mexico}` -> `value:Mexico}...30`
• `countryiso3code:MEX` -> `countryiso3code:MEX...31`
• `unit:"` -> `unit:"...34`
• `obs_status:"` -> `obs_status:"...35`
• `decimal:0}` -> `decimal:0}...36`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...37`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...38`
• `country:{id:MX` -> `country:{id:MX...39`
• `value:Mexico}` -> `value:Mexico}...40`
• `countryiso3code:MEX` -> `countryiso3code:MEX...41`
• `unit:"` -> `unit:"...44`
• `obs_status:"` -> `obs_status:"...45`
• `decimal:0}` -> `decimal:0}...46`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...47`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...48`
• `country:{id:MX` -> `country:{id:MX...49`
• `value:Mexico}` -> `value:Mexico}...50`
• `countryiso3code:MEX` -> `countryiso3code:MEX...51`
• `unit:"` -> `unit:"...54`
• `obs_status:"` -> `obs_status:"...55`
• `decimal:0}` -> `decimal:0}...56`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...57`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...58`
• `country:{id:MX` -> `country:{id:MX...59`
• `value:Mexico}` -> `value:Mexico}...60`
• `countryiso3code:MEX` -> `countryiso3code:MEX...61`
• `unit:"` -> `unit:"...64`
• `obs_status:"` -> `obs_status:"...65`
• `decimal:0}` -> `decimal:0}...66`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...67`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...68`
• `country:{id:MX` -> `country:{id:MX...69`
• `value:Mexico}` -> `value:Mexico}...70`
• `countryiso3code:MEX` -> `countryiso3code:MEX...71`
• `unit:"` -> `unit:"...74`
• `obs_status:"` -> `obs_status:"...75`
• `decimal:0}` -> `decimal:0}...76`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...77`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...78`
• `country:{id:MX` -> `country:{id:MX...79`
• `value:Mexico}` -> `value:Mexico}...80`
• `countryiso3code:MEX` -> `countryiso3code:MEX...81`
• `unit:"` -> `unit:"...84`
• `obs_status:"` -> `obs_status:"...85`
• `decimal:0}` -> `decimal:0}...86`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...87`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...88`
• `country:{id:MX` -> `country:{id:MX...89`
• `value:Mexico}` -> `value:Mexico}...90`
• `countryiso3code:MEX` -> `countryiso3code:MEX...91`
• `unit:"` -> `unit:"...94`
• `obs_status:"` -> `obs_status:"...95`
• `decimal:0}` -> `decimal:0}...96`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...97`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...98`
• `country:{id:MX` -> `country:{id:MX...99`
• `value:Mexico}` -> `value:Mexico}...100`
• `countryiso3code:MEX` -> `countryiso3code:MEX...101`
• `unit:"` -> `unit:"...104`
• `obs_status:"` -> `obs_status:"...105`
• `decimal:0}` -> `decimal:0}...106`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...107`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...108`
• `country:{id:MX` -> `country:{id:MX...109`
• `value:Mexico}` -> `value:Mexico}...110`
• `countryiso3code:MEX` -> `countryiso3code:MEX...111`
• `unit:"` -> `unit:"...114`
• `obs_status:"` -> `obs_status:"...115`
• `decimal:0}` -> `decimal:0}...116`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...117`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...118`
• `country:{id:MX` -> `country:{id:MX...119`
• `value:Mexico}` -> `value:Mexico}...120`
• `countryiso3code:MEX` -> `countryiso3code:MEX...121`
• `unit:"` -> `unit:"...124`
• `obs_status:"` -> `obs_status:"...125`
• `decimal:0}` -> `decimal:0}...126`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...127`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...128`
• `country:{id:MX` -> `country:{id:MX...129`
• `value:Mexico}` -> `value:Mexico}...130`
• `countryiso3code:MEX` -> `countryiso3code:MEX...131`
• `unit:"` -> `unit:"...134`
• `obs_status:"` -> `obs_status:"...135`
• `decimal:0}` -> `decimal:0}...136`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...137`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...138`
• `country:{id:MX` -> `country:{id:MX...139`
• `value:Mexico}` -> `value:Mexico}...140`
• `countryiso3code:MEX` -> `countryiso3code:MEX...141`
• `unit:"` -> `unit:"...144`
• `obs_status:"` -> `obs_status:"...145`
• `decimal:0}` -> `decimal:0}...146`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...147`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...148`
• `country:{id:MX` -> `country:{id:MX...149`
• `value:Mexico}` -> `value:Mexico}...150`
• `countryiso3code:MEX` -> `countryiso3code:MEX...151`
• `unit:"` -> `unit:"...154`
• `obs_status:"` -> `obs_status:"...155`
• `decimal:0}` -> `decimal:0}...156`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...157`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...158`
• `country:{id:MX` -> `country:{id:MX...159`
• `value:Mexico}` -> `value:Mexico}...160`
• `countryiso3code:MEX` -> `countryiso3code:MEX...161`
• `unit:"` -> `unit:"...164`
• `obs_status:"` -> `obs_status:"...165`
• `decimal:0}` -> `decimal:0}...166`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...167`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...168`
• `country:{id:MX` -> `country:{id:MX...169`
• `value:Mexico}` -> `value:Mexico}...170`
• `countryiso3code:MEX` -> `countryiso3code:MEX...171`
• `unit:"` -> `unit:"...174`
• `obs_status:"` -> `obs_status:"...175`
• `decimal:0}` -> `decimal:0}...176`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...177`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...178`
• `country:{id:MX` -> `country:{id:MX...179`
• `value:Mexico}` -> `value:Mexico}...180`
• `countryiso3code:MEX` -> `countryiso3code:MEX...181`
• `unit:"` -> `unit:"...184`
• `obs_status:"` -> `obs_status:"...185`
• `decimal:0}` -> `decimal:0}...186`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...187`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...188`
• `country:{id:MX` -> `country:{id:MX...189`
• `value:Mexico}` -> `value:Mexico}...190`
• `countryiso3code:MEX` -> `countryiso3code:MEX...191`
• `unit:"` -> `unit:"...194`
• `obs_status:"` -> `obs_status:"...195`
• `decimal:0}` -> `decimal:0}...196`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...197`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...198`
• `country:{id:MX` -> `country:{id:MX...199`
• `value:Mexico}` -> `value:Mexico}...200`
• `countryiso3code:MEX` -> `countryiso3code:MEX...201`
• `unit:"` -> `unit:"...204`
• `obs_status:"` -> `obs_status:"...205`
• `decimal:0}` -> `decimal:0}...206`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...207`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...208`
• `country:{id:MX` -> `country:{id:MX...209`
• `value:Mexico}` -> `value:Mexico}...210`
• `countryiso3code:MEX` -> `countryiso3code:MEX...211`
• `unit:"` -> `unit:"...214`
• `obs_status:"` -> `obs_status:"...215`
• `decimal:0}` -> `decimal:0}...216`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...217`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...218`
• `country:{id:MX` -> `country:{id:MX...219`
• `value:Mexico}` -> `value:Mexico}...220`
• `countryiso3code:MEX` -> `countryiso3code:MEX...221`
• `unit:"` -> `unit:"...224`
• `obs_status:"` -> `obs_status:"...225`
• `decimal:0}` -> `decimal:0}...226`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...227`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...228`
• `country:{id:MX` -> `country:{id:MX...229`
• `value:Mexico}` -> `value:Mexico}...230`
• `countryiso3code:MEX` -> `countryiso3code:MEX...231`
• `unit:"` -> `unit:"...234`
• `obs_status:"` -> `obs_status:"...235`
• `decimal:0}` -> `decimal:0}...236`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...237`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...238`
• `country:{id:MX` -> `country:{id:MX...239`
• `value:Mexico}` -> `value:Mexico}...240`
• `countryiso3code:MEX` -> `countryiso3code:MEX...241`
• `unit:"` -> `unit:"...244`
• `obs_status:"` -> `obs_status:"...245`
• `decimal:0}` -> `decimal:0}...246`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...247`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...248`
• `country:{id:MX` -> `country:{id:MX...249`
• `value:Mexico}` -> `value:Mexico}...250`
• `countryiso3code:MEX` -> `countryiso3code:MEX...251`
• `unit:"` -> `unit:"...254`
• `obs_status:"` -> `obs_status:"...255`
• `decimal:0}` -> `decimal:0}...256`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...257`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...258`
• `country:{id:MX` -> `country:{id:MX...259`
• `value:Mexico}` -> `value:Mexico}...260`
• `countryiso3code:MEX` -> `countryiso3code:MEX...261`
• `unit:"` -> `unit:"...264`
• `obs_status:"` -> `obs_status:"...265`
• `decimal:0}` -> `decimal:0}...266`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...267`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...268`
• `country:{id:MX` -> `country:{id:MX...269`
• `value:Mexico}` -> `value:Mexico}...270`
• `countryiso3code:MEX` -> `countryiso3code:MEX...271`
• `unit:"` -> `unit:"...274`
• `obs_status:"` -> `obs_status:"...275`
• `decimal:0}` -> `decimal:0}...276`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...277`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...278`
• `country:{id:MX` -> `country:{id:MX...279`
• `value:Mexico}` -> `value:Mexico}...280`
• `countryiso3code:MEX` -> `countryiso3code:MEX...281`
• `unit:"` -> `unit:"...284`
• `obs_status:"` -> `obs_status:"...285`
• `decimal:0}` -> `decimal:0}...286`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...287`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...288`
• `country:{id:MX` -> `country:{id:MX...289`
• `value:Mexico}` -> `value:Mexico}...290`
• `countryiso3code:MEX` -> `countryiso3code:MEX...291`
• `unit:"` -> `unit:"...294`
• `obs_status:"` -> `obs_status:"...295`
• `decimal:0}` -> `decimal:0}...296`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...297`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...298`
• `country:{id:MX` -> `country:{id:MX...299`
• `value:Mexico}` -> `value:Mexico}...300`
• `countryiso3code:MEX` -> `countryiso3code:MEX...301`
• `unit:"` -> `unit:"...304`
• `obs_status:"` -> `obs_status:"...305`
• `decimal:0}` -> `decimal:0}...306`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...307`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...308`
• `country:{id:MX` -> `country:{id:MX...309`
• `value:Mexico}` -> `value:Mexico}...310`
• `countryiso3code:MEX` -> `countryiso3code:MEX...311`
• `unit:"` -> `unit:"...314`
• `obs_status:"` -> `obs_status:"...315`
• `decimal:0}` -> `decimal:0}...316`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...317`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...318`
• `country:{id:MX` -> `country:{id:MX...319`
• `value:Mexico}` -> `value:Mexico}...320`
• `countryiso3code:MEX` -> `countryiso3code:MEX...321`
• `unit:"` -> `unit:"...324`
• `obs_status:"` -> `obs_status:"...325`
• `decimal:0}` -> `decimal:0}...326`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...327`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...328`
• `country:{id:MX` -> `country:{id:MX...329`
• `value:Mexico}` -> `value:Mexico}...330`
• `countryiso3code:MEX` -> `countryiso3code:MEX...331`
• `unit:"` -> `unit:"...334`
• `obs_status:"` -> `obs_status:"...335`
• `decimal:0}` -> `decimal:0}...336`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...337`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...338`
• `country:{id:MX` -> `country:{id:MX...339`
• `value:Mexico}` -> `value:Mexico}...340`
• `countryiso3code:MEX` -> `countryiso3code:MEX...341`
• `unit:"` -> `unit:"...344`
• `obs_status:"` -> `obs_status:"...345`
• `decimal:0}` -> `decimal:0}...346`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...347`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...348`
• `country:{id:MX` -> `country:{id:MX...349`
• `value:Mexico}` -> `value:Mexico}...350`
• `countryiso3code:MEX` -> `countryiso3code:MEX...351`
• `unit:"` -> `unit:"...354`
• `obs_status:"` -> `obs_status:"...355`
• `decimal:0}` -> `decimal:0}...356`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...357`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...358`
• `country:{id:MX` -> `country:{id:MX...359`
• `value:Mexico}` -> `value:Mexico}...360`
• `countryiso3code:MEX` -> `countryiso3code:MEX...361`
• `unit:"` -> `unit:"...364`
• `obs_status:"` -> `obs_status:"...365`
• `decimal:0}` -> `decimal:0}...366`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...367`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...368`
• `country:{id:MX` -> `country:{id:MX...369`
• `value:Mexico}` -> `value:Mexico}...370`
• `countryiso3code:MEX` -> `countryiso3code:MEX...371`
• `unit:"` -> `unit:"...374`
• `obs_status:"` -> `obs_status:"...375`
• `decimal:0}` -> `decimal:0}...376`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...377`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...378`
• `country:{id:MX` -> `country:{id:MX...379`
• `value:Mexico}` -> `value:Mexico}...380`
• `countryiso3code:MEX` -> `countryiso3code:MEX...381`
• `unit:"` -> `unit:"...384`
• `obs_status:"` -> `obs_status:"...385`
• `decimal:0}` -> `decimal:0}...386`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...387`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...388`
• `country:{id:MX` -> `country:{id:MX...389`
• `value:Mexico}` -> `value:Mexico}...390`
• `countryiso3code:MEX` -> `countryiso3code:MEX...391`
• `unit:"` -> `unit:"...394`
• `obs_status:"` -> `obs_status:"...395`
• `decimal:0}` -> `decimal:0}...396`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...397`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...398`
• `country:{id:MX` -> `country:{id:MX...399`
• `value:Mexico}` -> `value:Mexico}...400`
• `countryiso3code:MEX` -> `countryiso3code:MEX...401`
• `unit:"` -> `unit:"...404`
• `obs_status:"` -> `obs_status:"...405`
• `decimal:0}` -> `decimal:0}...406`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...407`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...408`
• `country:{id:MX` -> `country:{id:MX...409`
• `value:Mexico}` -> `value:Mexico}...410`
• `countryiso3code:MEX` -> `countryiso3code:MEX...411`
• `unit:"` -> `unit:"...414`
• `obs_status:"` -> `obs_status:"...415`
• `decimal:0}` -> `decimal:0}...416`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...417`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...418`
• `country:{id:MX` -> `country:{id:MX...419`
• `value:Mexico}` -> `value:Mexico}...420`
• `countryiso3code:MEX` -> `countryiso3code:MEX...421`
• `unit:"` -> `unit:"...424`
• `obs_status:"` -> `obs_status:"...425`
• `decimal:0}` -> `decimal:0}...426`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...427`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...428`
• `country:{id:MX` -> `country:{id:MX...429`
• `value:Mexico}` -> `value:Mexico}...430`
• `countryiso3code:MEX` -> `countryiso3code:MEX...431`
• `unit:"` -> `unit:"...434`
• `obs_status:"` -> `obs_status:"...435`
• `decimal:0}` -> `decimal:0}...436`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...437`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...438`
• `country:{id:MX` -> `country:{id:MX...439`
• `value:Mexico}` -> `value:Mexico}...440`
• `countryiso3code:MEX` -> `countryiso3code:MEX...441`
• `unit:"` -> `unit:"...444`
• `obs_status:"` -> `obs_status:"...445`
• `decimal:0}` -> `decimal:0}...446`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...447`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...448`
• `country:{id:MX` -> `country:{id:MX...449`
• `value:Mexico}` -> `value:Mexico}...450`
• `countryiso3code:MEX` -> `countryiso3code:MEX...451`
• `unit:"` -> `unit:"...454`
• `obs_status:"` -> `obs_status:"...455`
• `decimal:0}` -> `decimal:0}...456`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...457`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...458`
• `country:{id:MX` -> `country:{id:MX...459`
• `value:Mexico}` -> `value:Mexico}...460`
• `countryiso3code:MEX` -> `countryiso3code:MEX...461`
• `unit:"` -> `unit:"...464`
• `obs_status:"` -> `obs_status:"...465`
• `decimal:0}` -> `decimal:0}...466`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...467`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...468`
• `country:{id:MX` -> `country:{id:MX...469`
• `value:Mexico}` -> `value:Mexico}...470`
• `countryiso3code:MEX` -> `countryiso3code:MEX...471`
• `unit:"` -> `unit:"...474`
• `obs_status:"` -> `obs_status:"...475`
• `decimal:0}` -> `decimal:0}...476`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...477`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...478`
• `country:{id:MX` -> `country:{id:MX...479`
• `value:Mexico}` -> `value:Mexico}...480`
• `countryiso3code:MEX` -> `countryiso3code:MEX...481`
• `unit:"` -> `unit:"...484`
• `obs_status:"` -> `obs_status:"...485`
• `decimal:0}` -> `decimal:0}...486`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...487`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...488`
• `country:{id:MX` -> `country:{id:MX...489`
• `value:Mexico}` -> `value:Mexico}...490`
• `countryiso3code:MEX` -> `countryiso3code:MEX...491`
• `unit:"` -> `unit:"...494`
• `obs_status:"` -> `obs_status:"...495`
• `decimal:0}` -> `decimal:0}...496`
• `{"indicator":{"id":"NY.GDP.MKTP.CD"` ->
  `{"indicator":{"id":"NY.GDP.MKTP.CD"...497`
• `value:GDP (current US$)}` -> `value:GDP (current US$)}...498`
• `country:{id:MX` -> `country:{id:MX...499`
• `value:Mexico}` -> `value:Mexico}...500`
• `countryiso3code:MEX` -> `countryiso3code:MEX...501`
• `unit:"` -> `unit:"...504`

In [57]:
datos_pib

   pais anio pib_usd
1  MEX  2025 1.832641e+12
2  MEX  2024 1.830489e+12
3  MEX  2023 1.794410e+12
4  MEX  2022 1.466935e+12
5  MEX  2021 1.316569e+12
6  MEX  2020 1.121065e+12
7  MEX  2019 1.304106e+12
8  MEX  2018 1.256300e+12
9  MEX  2017 1.190721e+12
10 MEX  2016 1.112233e+12
11 MEX  2015 1.213294e+12
12 MEX  2014 1.364508e+12
13 MEX  2013 1.327436e+12
14 MEX  2012 1.255110e+12
15 MEX  2011 1.229014e+12
16 MEX  2010 1.105424e+12
17 MEX  2009 9.434374e+11
18 MEX  2008 1.161553e+12
19 MEX  2007 1.102356e+12
20 MEX  2006 1.020265e+12
21 MEX  2005 9.175719e+11
22 MEX  2004 8.194592e+11
23 MEX  2003 7.655500e+11
24 MEX  2002 8.106661e+11
25 MEX  2001 7.960646e+11
26 MEX  2000 7.420613e+11
27 MEX  1999 6.312494e+11
28 MEX  1998 5.574611e+11
29 MEX  1997 5.234495e+11
30 MEX  1996 4.321579e+11
⋮  ⋮    ⋮    ⋮
37 MEX  1989 221403098267
38 MEX  1988 181611150497
39 MEX  1987 147542558209
40 MEX  1986 134556034673
41 MEX  1985 195241069482
42 MEX  1984 184230754105
43 MEX  1983 156167000433
44 MEX  1982 184602611610
45 MEX  1981 263797827860
46 MEX  1980 205577055466
47 MEX  1979 134531900899
48 MEX  1978 102648570299
49 MEX  1977  81912018784
50 MEX  1976  88875923765
51 MEX  1975  88000000000
52 MEX  1974  72000000000
53 MEX  1973  55280000000
54 MEX  1972  45200000000
55 MEX  1971  39200000000
56 MEX  1970  35520000000
57 MEX  1969  32480000000
58 MEX  1968  29360000000
59 MEX  1967  26560000000
60 MEX  1966  24320000000
61 MEX  1965  21840000000
62 MEX  1964  20080000000
63 MEX  1963  16960000000
64 MEX  1962  15200000000
65 MEX  1961  14160000000
66 MEX  1960  13040000000

In [52]:
datos_pib <- datos_crudos |>
  select(
    pais = countryiso3code,
    anio = date,
    pib_usd = value
  )

In [48]:
glimpse(datos_pib)

Rows: 66
Columns: 3
$ pais    <chr> "MEX", "MEX", "MEX", "MEX", "MEX", "MEX", "MEX", "MEX", "MEX",…
$ anio    <chr> "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018"…
$ pib_usd <dbl> 1.832641e+12, 1.830489e+12, 1.794410e+12, 1.466935e+12, 1.3165…

In [49]:
head(datos_pib)

  pais anio pib_usd
1 MEX  2025 1.832641e+12
2 MEX  2024 1.830489e+12
3 MEX  2023 1.794410e+12
4 MEX  2022 1.466935e+12
5 MEX  2021 1.316569e+12
6 MEX  2020 1.121065e+12

### Escala de medicion de las variables
pais (Código ISO del país): Cualitativa nominal. Son etiquetas o categorías que no tienen un orden matemático ni jerarquía.

anio (Año del registro): Cuantitativa discreta / Escala de intervalo. Son números enteros que representan periodos cronológicos de tiempo.

pib_usd (Valor del PIB en USD): Cuantitativa continua / Escala de razón. Son números que pueden tener decimales y poseen un cero absoluto real (donde cero significaría total ausencia de producción).

###Las cuatro preguntas

**¿Qué pregunta busca responder esta investigación?**
Esta investigación busca responder cuál ha sido la evolución, la trayectoria de crecimiento y la volatilidad del Producto Interno Bruto (PIB) de México a lo largo de las últimas décadas.

**¿Por qué es relevante esta pregunta para los Negocios Internacionales?**
Este análisis es fundamental porque el PIB es un indicador clave del atractivo de inversión y la salud del mercado interno. Una economía estable atrae la Inversión Extranjera Directa y permite a las empresas transnacionales evaluar la viabilidad de expansión o proyectar la demanda. Además, al analizar los datos en dólares, los especialistas pueden medir la vulnerabilidad del país frente a crisis globales y devaluaciones históricas.

**¿Qué datos específicos se analizarán?**
Se analizarán los registros anuales de la economía de México extraídos de los Indicadores del Desarrollo Mundial mediante la API oficial del Banco Mundial. Específicamente, se utilizarán tres variables: el país de observación medido en escala cualitativa nominal, el año de registro cronológico en escala cuantitativa de intervalo, y el valor total de la producción formal en dólares actuales, que corresponde a una escala cuantitativa continua y de razón.

**¿Cuáles son los límites de esta investigación?**
Los límites principales radican en que el cálculo oficial del PIB excluye la economía informal y el trabajo no remunerado. Además, al utilizar dólares corrientes, las cifras pueden sufrir distorsiones por la inflación o fluctuaciones en el tipo de cambio, sin reflejar necesariamente cambios en la producción real. Finalmente, este indicador global no muestra cómo se distribuye la riqueza ni refleja la calidad de vida o la desigualdad social en el país.